//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolestanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalcTariffTbl
    {
        public short CalLawId { get; set; }
        public decimal TrfCode { get; set; }
        public decimal TrfHCode { get; set; }
        public byte TrfType { get; set; }
        public Nullable<short> LawItem { get; set; }
        public Nullable<short> SubLawItem { get; set; }
        public string TrfName { get; set; }
        public bool IgnoreSeason { get; set; }
        public bool IsDisable { get; set; }
        public bool IsPenaltyOff { get; set; }
        public decimal FreeTrfCode { get; set; }
        public decimal DiscountPercent { get; set; }
        public bool OffMinDemand { get; set; }
        public Nullable<int> Tempfld1 { get; set; }
        public Nullable<int> Tempfld2 { get; set; }
        public Nullable<int> Tempfld3 { get; set; }
        public Nullable<int> Tempfld4 { get; set; }
        public Nullable<int> Tempfld5 { get; set; }
        public Nullable<int> Tempfld6 { get; set; }
        public Nullable<int> Tempfld7 { get; set; }
        public Nullable<int> Tempfld8 { get; set; }
        public Nullable<int> Tempfld9 { get; set; }
        public Nullable<int> Tempfld10 { get; set; }
        public Nullable<int> Tempfld11 { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual CalcTarrifHeaderTbl CalcTarrifHeaderTbl { get; set; }
    }
}
