//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolestanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalcRgnCityByTrfTempView
    {
        public short CoCode { get; set; }
        public short RgnCode { get; set; }
        public short CityCode { get; set; }
        public short CalLawId { get; set; }
        public decimal TrfHCode { get; set; }
        public byte TrfType { get; set; }
        public int TRID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string TrName { get; set; }
        public Nullable<decimal> TrCoef { get; set; }
        public Nullable<byte> trtype { get; set; }
        public decimal AllowedUsage { get; set; }
        public Nullable<decimal> TmpFld1 { get; set; }
        public Nullable<decimal> TmpFld2 { get; set; }
        public Nullable<decimal> TmpFld3 { get; set; }
    }
}
