//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolestanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalcTempratureRegionView
    {
        public int TRID { get; set; }
        public short CalLawId { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string TrName { get; set; }
        public Nullable<decimal> TrCoef { get; set; }
        public string trtype { get; set; }
        public string LawName { get; set; }
    }
}
