//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolestanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalcTempratureRegionTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CalcTempratureRegionTbl()
        {
            this.CalcRateTbls = new HashSet<CalcRateTbl>();
            this.CalcSeasonDefineTbls = new HashSet<CalcSeasonDefineTbl>();
            this.CalcTarrifForGeoTempTbls = new HashSet<CalcTarrifForGeoTempTbl>();
        }
    
        public int TRID { get; set; }
        public short CalLawId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string TrName { get; set; }
        public Nullable<decimal> TrCoef { get; set; }
        public Nullable<byte> trtype { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public decimal AllowedUsage { get; set; }
        public Nullable<decimal> TmpFld1 { get; set; }
        public Nullable<decimal> TmpFld2 { get; set; }
        public Nullable<decimal> TmpFld3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalcRateTbl> CalcRateTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalcSeasonDefineTbl> CalcSeasonDefineTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalcTarrifForGeoTempTbl> CalcTarrifForGeoTempTbls { get; set; }
    }
}
