//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolestanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalcTarrifItemsTbl
    {
        public short CalLawId { get; set; }
        public decimal TrfCode { get; set; }
        public decimal TrfHCode { get; set; }
        public byte TrfType { get; set; }
        public Nullable<short> LawItem { get; set; }
        public Nullable<short> SubLawItem { get; set; }
        public byte PresureCode { get; set; }
        public decimal SelCode { get; set; }
        public string TrfName { get; set; }
        public string LawItemCode { get; set; }
        public Nullable<int> Tempfld1 { get; set; }
        public Nullable<int> Tempfld2 { get; set; }
        public bool IgnoreSeason { get; set; }
        public bool IsDisable { get; set; }
        public bool IsPenaltyOff { get; set; }
        public decimal FreeTrfCode { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
