//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolestanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalcPenaltyRateTbl
    {
        public short CalLawId { get; set; }
        public decimal TrfHCode { get; set; }
        public byte TrfType { get; set; }
        public int TRID { get; set; }
        public byte PresureCode { get; set; }
        public short LawItem { get; set; }
        public short SubLawItem { get; set; }
        public decimal SelCode { get; set; }
        public decimal USE_STEP { get; set; }
        public byte NomratorType { get; set; }
        public Nullable<decimal> NegPwrRt { get; set; }
        public Nullable<decimal> PWR_0_RT_COEF { get; set; }
        public Nullable<decimal> PWR_1_RT_COEF { get; set; }
        public Nullable<decimal> Neg_2_PWR_RT { get; set; }
        public Nullable<decimal> SRPS_AMT { get; set; }
        public Nullable<int> Tempfld1 { get; set; }
        public Nullable<int> Tempfld2 { get; set; }
        public Nullable<int> Tempfld3 { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual CalcRateTbl CalcRateTbl { get; set; }
    }
}
