//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolestanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalcRateTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CalcRateTbl()
        {
            this.CalcPenaltyRateTbls = new HashSet<CalcPenaltyRateTbl>();
            this.CalcRateCodeTbls = new HashSet<CalcRateCodeTbl>();
        }
    
        public short CalLawId { get; set; }
        public decimal TrfHCode { get; set; }
        public byte TrfType { get; set; }
        public int TRID { get; set; }
        public byte PresureCode { get; set; }
        public short LawItem { get; set; }
        public short SubLawItem { get; set; }
        public decimal PHS_1_SBSC_FIX_AMT { get; set; }
        public decimal PHS_3_SBSC_FIX_AMT { get; set; }
        public decimal PHS_1_MIN_AMT { get; set; }
        public decimal PHS_3_MIN_AMT { get; set; }
        public decimal TAX_PT { get; set; }
        public decimal TAX_SBSC_CMPT_COEF { get; set; }
        public decimal TV_MM_RT { get; set; }
        public decimal TV_INCD_USE_MIN { get; set; }
        public decimal ACT1_RT_MAX { get; set; }
        public decimal ACT2_RT_MAX { get; set; }
        public decimal ACT3_RT_MAX { get; set; }
        public decimal RACT_RT_MAX { get; set; }
        public decimal PWR_RT_MAX_TRF1 { get; set; }
        public decimal PWR_CAL_COEF { get; set; }
        public decimal PEEK_COEF { get; set; }
        public decimal FRIDAY_COEF { get; set; }
        public decimal DISABLE_DISCOUNT_AMT { get; set; }
        public decimal DISABLE_DISCOUNT_KW { get; set; }
        public decimal NONINDUSTRIAL_PENALTY_COEF { get; set; }
        public decimal PWR_ICN_EXPIRE_PENALTY_COEF { get; set; }
        public decimal MaxAllowedUse { get; set; }
        public decimal maxrateperkw { get; set; }
        public decimal VILLAGE_RATE { get; set; }
        public decimal VillageInsurance { get; set; }
        public decimal CityInsurance { get; set; }
        public Nullable<decimal> AvarezBarghRate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalcPenaltyRateTbl> CalcPenaltyRateTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalcRateCodeTbl> CalcRateCodeTbls { get; set; }
        public virtual CalcTarrifHeaderTbl CalcTarrifHeaderTbl { get; set; }
        public virtual CalcTempratureRegionTbl CalcTempratureRegionTbl { get; set; }
    }
}
