//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolestanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVNBranchDataView
    {
        public int BranchCode { get; set; }
        public Nullable<int> OwnerCode { get; set; }
        public string OwnerFamily { get; set; }
        public string OwnerName { get; set; }
        public byte BranchTypeCode { get; set; }
        public Nullable<byte> Phs { get; set; }
        public int Amp { get; set; }
        public Nullable<byte> VoltCode { get; set; }
        public Nullable<decimal> trfHeader { get; set; }
        public string HomeAdderss { get; set; }
        public Nullable<decimal> HomePoNum { get; set; }
        public short FmlCode { get; set; }
        public byte SelCode { get; set; }
        public int BranchSrl { get; set; }
        public short RgnCode { get; set; }
        public short CityCode { get; set; }
        public Nullable<short> VillageCode { get; set; }
        public decimal PwrCnt { get; set; }
        public Nullable<decimal> OrgCode { get; set; }
        public int RdgSrl { get; set; }
        public Nullable<decimal> PwrIcn { get; set; }
        public Nullable<System.DateTime> PwrIcnExpDate { get; set; }
        public Nullable<decimal> ActTypeCode { get; set; }
        public Nullable<byte> BranchStatCode { get; set; }
        public Nullable<long> CrDBBranchSale { get; set; }
        public decimal CrDbTot { get; set; }
        public string ValidationStatusName { get; set; }
        public Nullable<int> OfficeAddressCode { get; set; }
        public Nullable<int> HomeAddressCode { get; set; }
        public Nullable<int> BranchAddressCode { get; set; }
        public string DecodeBranchKindCode { get; set; }
        public Nullable<byte> BranchKindCode { get; set; }
        public string GeoAreaCodeName { get; set; }
        public Nullable<short> PostType { get; set; }
        public byte PresureCode { get; set; }
        public Nullable<byte> ServiceCode { get; set; }
        public Nullable<System.DateTime> BranchCntractDate { get; set; }
        public Nullable<System.DateTime> BranchCreatDate { get; set; }
        public Nullable<System.DateTime> TmpExpireDate { get; set; }
        public string OwnerNatCode { get; set; }
        public Nullable<int> ShomareShenasname { get; set; }
        public string IssuedFrom { get; set; }
        public string FatherName { get; set; }
        public string Email { get; set; }
        public decimal TrfCode { get; set; }
        public short WorkDayCode { get; set; }
        public short RdrCode { get; set; }
        public Nullable<byte> InstlCntrCode { get; set; }
        public Nullable<System.DateTime> InstallDate3Rate { get; set; }
        public Nullable<byte> ChngCntrCode { get; set; }
        public Nullable<long> CrDbOtherCost { get; set; }
        public Nullable<short> SpecialCode { get; set; }
        public string Adress { get; set; }
        public string MobileNo { get; set; }
        public string FixedTel { get; set; }
        public short CoCode { get; set; }
        public string FabrikNumber { get; set; }
        public Nullable<short> PrdcrCode { get; set; }
        public Nullable<byte> CntrKind { get; set; }
        public string EshterakCode { get; set; }
        public string IdentityCode { get; set; }
        public byte GeoState { get; set; }
        public Nullable<decimal> TrfHCode { get; set; }
        public Nullable<decimal> SfscTrfCode { get; set; }
        public Nullable<byte> CategoryCode { get; set; }
        public Nullable<decimal> Expr1 { get; set; }
        public Nullable<int> CounterCode { get; set; }
        public Nullable<short> QtyDgt { get; set; }
        public Nullable<System.DateTime> UpdInstDate { get; set; }
        public Nullable<System.DateTime> LastReadDate { get; set; }
        public Nullable<System.DateTime> CntrUninsDate { get; set; }
        public Nullable<double> CntrCoef { get; set; }
        public Nullable<short> CounterTypeCode { get; set; }
        public Nullable<byte> CntrStatCode { get; set; }
        public Nullable<byte> DurationType { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<byte> TimerCode { get; set; }
        public Nullable<System.DateTime> UpdUninstDate { get; set; }
        public short SmartCounter { get; set; }
        public Nullable<byte> CalCode { get; set; }
        public string PolompNum { get; set; }
        public Nullable<byte> TrfType { get; set; }
        public Nullable<int> ownerTypeCode { get; set; }
        public Nullable<short> GeoAreaCode { get; set; }
        public Nullable<long> TmpFld6 { get; set; }
        public Nullable<long> NewBranchCode { get; set; }
        public decimal RealPower { get; set; }
        public Nullable<int> DomainCode { get; set; }
        public int DimandMeter { get; set; }
        public Nullable<short> CustomerStatus { get; set; }
        public string Alley { get; set; }
        public Nullable<double> LatitueX { get; set; }
        public Nullable<double> LongitudeY { get; set; }
        public System.DateTime BranchModifiedDate { get; set; }
        public int BuiltUpArea { get; set; }
        public Nullable<decimal> BillId { get; set; }
        public Nullable<int> TmpFld5 { get; set; }
        public string Codeab { get; set; }
        public Nullable<System.DateTime> LstPayLimitDate { get; set; }
        public Nullable<System.DateTime> LastRcptDate { get; set; }
        public string FixedTel2 { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Expr2 { get; set; }
        public Nullable<System.DateTime> LetterExpireDate { get; set; }
        public string LetterAndicator { get; set; }
        public Nullable<System.DateTime> LetterDate { get; set; }
        public string IndivisualCode { get; set; }
        public string Fax { get; set; }
    }
}
