//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolestanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TvnCounterView
    {
        public int BranchCode { get; set; }
        public int CounterCode { get; set; }
        public Nullable<byte> BranchTypeCode { get; set; }
        public Nullable<short> CoCode { get; set; }
        public short RgnCode { get; set; }
        public short CityCode { get; set; }
        public short VillageCode { get; set; }
        public Nullable<short> WorkDayCode { get; set; }
        public Nullable<short> RdrCode { get; set; }
        public short CounterTypeCode { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public string FabrikNumber { get; set; }
        public Nullable<byte> TimerCode { get; set; }
        public string TimerFabNumber { get; set; }
        public int DomainCode { get; set; }
        public double DemandCoef { get; set; }
        public Nullable<System.DateTime> CntrUninsDate { get; set; }
        public Nullable<System.DateTime> UpdUninstDate { get; set; }
        public Nullable<byte> CntrStatCode { get; set; }
        public Nullable<short> ChngReson { get; set; }
        public Nullable<int> ChangeTypeCode { get; set; }
        public double CntrCoef { get; set; }
        public short PrdcrCode { get; set; }
        public Nullable<byte> CntrKind { get; set; }
        public short QtyDgt { get; set; }
        public Nullable<byte> CalCode { get; set; }
        public System.DateTime UpdInstDate { get; set; }
        public Nullable<int> InstallerCode { get; set; }
        public Nullable<System.DateTime> LastReadDate { get; set; }
        public Nullable<System.DateTime> VirtualLastReadDate { get; set; }
        public string PolompNum { get; set; }
        public Nullable<decimal> CtInitialVolt { get; set; }
        public Nullable<decimal> PtInitialVolt { get; set; }
        public Nullable<decimal> CtSecondVolt { get; set; }
        public Nullable<decimal> PtSecondVolt { get; set; }
        public string Feeder { get; set; }
        public string Post { get; set; }
        public Nullable<int> InstallRequestCode { get; set; }
        public Nullable<int> UnInstallRequestCode { get; set; }
        public Nullable<int> TmpFld1 { get; set; }
        public Nullable<short> TmpFld2 { get; set; }
        public Nullable<long> TmpFld3 { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<short> SmartCounter { get; set; }
    }
}
