//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolestanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVNF50FormView
    {
        public int BranchCode { get; set; }
        public Nullable<System.DateTime> BnkDate { get; set; }
        public Nullable<System.DateTime> RcptDateTime { get; set; }
        public short RcptType { get; set; }
        public Nullable<byte> ReceiptKind { get; set; }
        public string IEFileName { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public long SRCode { get; set; }
        public decimal RcptAmt { get; set; }
        public decimal SaleCode { get; set; }
        public string BillID { get; set; }
        public string PaymentID { get; set; }
        public int BankCode { get; set; }
        public int BankBranchCode { get; set; }
        public int RefrenceCode { get; set; }
        public short RgnCode { get; set; }
        public short CityCode { get; set; }
        public short CoCode { get; set; }
        public int ReceiptSource { get; set; }
    }
}
